coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 5%
        # TODO should remove 'informational: true' after first functional version
        informational: true

comment:
  require_changes: true
