codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  range: 70..90
  status:
    project:
      default:
        target: 85%
        threshold: 5%

comment:
  layout: diff, files
  require_changes: true
