name: link-to-checklist

on:
  workflow_dispatch:
  push:
  pull_request_target:
    types: [opened]

permissions:
  pull-requests: write

jobs:
  add-review-checklist:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Add review checklist
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const review_checklist = fs.readFileSync('.github/ingestion-review-checklist.md', 'utf8');

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: review_checklist,
            });
