name: test-condition

on:
  workflow_dispatch:
  pull_request_target:
    types: [opened]

jobs:
  print_info:
    if: ${{ github.event_name == 'pull_request_target' && github.event.action == 'opened' && startsWith(github.event.pull_request.title, 'ingestion') }}
    runs-on: ubuntu-latest
    steps:
      - name: Print event details
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Action: ${{ github.event.action }}"
          echo "PR Title: ${{ github.event.pull_request.title }}"